# Generated by Django 5.1.5 on 2025-01-18 19:47

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Укажите email', max_length=254, unique=True, verbose_name='Email')),
                ('country', models.CharField(help_text='Укажите страну', max_length=100, verbose_name='Страна')),
                ('citi', models.CharField(help_text='Укажите город', max_length=100, verbose_name='Город')),
                ('street', models.CharField(help_text='Укажите название улицы', max_length=100, verbose_name='Улица')),
                ('house_number', models.CharField(help_text='Укажите номер дома', max_length=20, verbose_name='Номер дома')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Введите номер телефона', max_length=128, null=True, region=None, unique=True, verbose_name='Номер телефона')),
            ],
        ),
    ]
