# Generated by Django 5.1.5 on 2025-01-29 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='citi',
            new_name='city',
        ),
    ]
