# Generated by Django 5.1.5 on 2025-01-18 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network_name', models.CharField(help_text='Введите название поставщика', max_length=200, verbose_name='Название поставщика')),
                ('debt', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Долг перед поставщиком')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания')),
                ('contact', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_contact', to='contacts.contact', verbose_name='Контакт')),
                ('product', models.ManyToManyField(related_name='suppliers', to='products.product', verbose_name='Продукт')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='suppliers.supplier', verbose_name='Поставщик')),
            ],
        ),
    ]
