# Generated by Django 5.1.5 on 2025-01-19 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='debt',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, editable=False, max_digits=12, null=True, verbose_name='Долг перед поставщиком'),
        ),
    ]
