# Generated by Django 5.1.5 on 2025-01-24 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0002_alter_supplier_debt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplier',
            old_name='level',
            new_name='hierarchy_level',
        ),
        migrations.AlterField(
            model_name='supplier',
            name='debt',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=12, verbose_name='Долг перед поставщиком'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='supplier',
            field=models.ForeignKey(blank=True, help_text='Поставщик, который закупает товар у другого поставщика', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='suppliers.supplier', verbose_name='Поставщик'),
        ),
    ]
