# Generated by Django 5.1.5 on 2025-01-24 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0003_rename_level_supplier_hierarchy_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='hierarchy_level',
            field=models.IntegerField(choices=[(0, 'Завод'), (1, 'Розничная сеть'), (2, 'Индивидуальный предприниматель')], help_text='Уровень иерархии поставщика', verbose_name='Уровень иерархии'),
        ),
    ]
