# Generated by Django 5.1.5 on 2025-01-29 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0004_alter_supplier_hierarchy_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='supplier',
            field=models.ForeignKey(blank=True, help_text='Поставщик, который закупает товар у другого поставщика', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client', to='suppliers.supplier', verbose_name='Поставщик'),
        ),
    ]
