# Generated by Django 5.1.5 on 2025-01-29 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0005_alter_supplier_supplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='hierarchy_level',
            field=models.IntegerField(choices=[(0, 'Завод'), (1, 'Розничная сеть'), (2, 'Индивидуальный предприниматель')], editable=False, help_text='Уровень иерархии поставщика', null=True, verbose_name='Уровень иерархии'),
        ),
    ]
