# Generated by Django 5.1.5 on 2025-01-18 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Введите название продукта', max_length=255, verbose_name='Название продукта')),
                ('model', models.CharField(help_text='Укажите модель продукта', max_length=100, verbose_name='Модель продукта')),
                ('release_date', models.DateField(help_text='Укажите дату выхода продукции на рынок', verbose_name='Дата выхода продукта на рынок')),
                ('image', models.ImageField(blank=True, help_text='Загрузите изображение продукта', null=True, upload_to='products/images/', verbose_name='Изображение продукта')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
    ]
