# Generated by Django 5.1.5 on 2025-01-29 15:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('suppliers', '0007_alter_supplier_supplier'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Введите название продукта', max_length=255, verbose_name='Название продукта')),
                ('model', models.CharField(help_text='Укажите модель продукта', max_length=100, verbose_name='Модель продукта')),
                ('price', models.DecimalField(decimal_places=2, help_text='Укажите цену продукта', max_digits=12, verbose_name='Цена продукта')),
                ('description', models.TextField(blank=True, help_text='Введите описание продукта', null=True, verbose_name='Описание продукта')),
                ('release_date', models.DateField(blank=True, help_text='Укажите дату выхода продукции на рынок', null=True, verbose_name='Дата выхода продукта на рынок')),
                ('image', models.ImageField(blank=True, help_text='Загрузите изображение продукта', null=True, upload_to='products/images/', verbose_name='Изображение продукта')),
                ('created_by', models.ForeignKey(help_text='Пользователь создавший продукт', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_products', to=settings.AUTH_USER_MODEL, verbose_name='Администратор каталога')),
                ('supplier', models.ForeignKey(help_text='Выберите поставщика', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='suppliers.supplier', verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
    ]
