# Generated by Django 5.1.5 on 2025-02-09 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('suppliers', '0007_alter_supplier_supplier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='supplier',
        ),
        migrations.AddField(
            model_name='product',
            name='supplier',
            field=models.ManyToManyField(help_text='Выберите поставщика', related_name='products', to='suppliers.supplier', verbose_name='Поставщик'),
        ),
    ]
